image: python:3.8

before_script:
  - export GITLAB_TOKEN=$CI_JOB_TOKEN
  - export GITLAB_USERNAME='gitlab-ci-token'
  - python -m venv venv
  - source venv/bin/activate
  - pip install .[dev]

stages:
  - lint
  - test

linting:
  stage: lint
  script: flake8 src

run_on_bucket:
  variables:
    OUTPUT_DIR: "./output/$CI_JOB_NAME"
  script: python src/neuron_morphology/validation/quality_metric_resource.py --token=$SA_TOKEN --output_dir=$OUTPUT_DIR
  artifacts:
    paths:
      - "$OUTPUT_DIR/*"