image: python:3.8

before_script:
  - export GITLAB_TOKEN=$CI_JOB_TOKEN
  - export GITLAB_USERNAME='gitlab-ci-token'
  - python -m venv venv
  - source venv/bin/activate
  - pip install .[dev]

stages:
  - lint
  - test

#linting:
#  stage: lint
#  script: flake8 src

run_on_bucket:
  rules:
    - when: manual
  variables:
    OUTPUT_DIR: "./output/$CI_COMMIT_TIMESTAMP"
  parallel:
    matrix:
      - BUCKET: bbp-external/seu
      - BUCKET: bbp/mouselight
      - BUCKET: public/sscx
      - BUCKET: public/thalamus
      - BUCKET: public/hippocampus
  script:
  - > 
    python src/neuron_morphology/validation/quality_metric_resource.py 
    --token $SA_TOKEN --output_dir $OUTPUT_DIR --bucket $BUCKET --curated yes
  artifacts:
    paths:
      - "$OUTPUT_DIR"


brain_region:
  rules:
    - when: manual
  variables:
    OUTPUT_DIR: "./output/$CI_COMMIT_TIMESTAMP"
  parallel:
    matrix:
      - BUCKET: bbp-external/seu
  script:
  - > 
    python src/neuron_morphology/validation/region_comparison.py 
    --token $SA_TOKEN --output_dir $OUTPUT_DIR --bucket $BUCKET --curated both
  artifacts:
    paths:
      - "$OUTPUT_DIR"

check_links:
  rules:
    - when: manual
  variables:
    OUTPUT_DIR: "./output/$CI_COMMIT_TIMESTAMP"
  parallel:
    matrix:
      - BUCKET: bbp-external/seu
      - BUCKET: bbp/mouselight
      - BUCKET: public/sscx
      - BUCKET: public/thalamus
      - BUCKET: public/hippocampus
  script:
  - > 
    python src/neuron_morphology/validation/check_links.py 
    --token $SA_TOKEN --output_dir $OUTPUT_DIR --bucket $BUCKET --curated both
  artifacts:
    paths:
      - "$OUTPUT_DIR"