image: python:3.8

variables:
  REALLY_UPDATE:
    value: "no"
    description: "When running pipelines that can push data into Nexus, whether the pipeline is ran just for reports or also for updates of data - Valid values: yes, no"
  LIMIT:
    value: "10000"
    description: "When querying, max number of results to get (useful for testing) - Valid values: an integer"
  STAGING:
    value: "yes"
    description: "Whether to push in staging or push in production (notes: 1. This is only relevant if REALLY_UPDATE = yes 2. Querying only happens in production) - Valid values: yes, no"
  CURATED:
    value: "both"
    description: "Whether only curated data is selected or all - Valid values: both, yes"
  KUBERNETES_MEMORY_LIMIT: 8Gi
  KUBERNETES_MEMORY_REQUEST: 8Gi
  KUBERNETES_CPU_LIMIT: 3
  KUBERNETES_CPU_REQUEST: 3

before_script:
  - export GITLAB_TOKEN=$CI_JOB_TOKEN
  - export GITLAB_USERNAME='gitlab-ci-token'
  - python -m venv venv
  - source venv/bin/activate
  - pip install .[dev]
  - echo REALLY_UPDATE ${REALLY_UPDATE}
  - echo LIMIT ${LIMIT}
  - echo STAGING ${STAGING}
  - echo CURATED ${CURATED}

stages:
  - lint
  - test

# linting:
#  stage: lint
#  script: flake8 src/schemas

check_morphologies_schema:
  rules:
    - when: manual
  variables:
    OUTPUT_DIR: "./output/$CI_COMMIT_TIMESTAMP"
  parallel:
    matrix:
      - BUCKET: bbp-external/seu
      - BUCKET: bbp/mouselight
      - BUCKET: public/sscx
      - BUCKET: public/thalamus
      - BUCKET: public/hippocampus
      - BUCKET: bbp/mmb-point-neuron-framework-model

  script:
  - > 
    python src/neuron_morphology/validation/check_schema.py 
    --username $SA_USERNAME --password $SA_PASSWORD --output_dir $OUTPUT_DIR --bucket $BUCKET --curated $CURATED
  artifacts:
    paths:
      - "$OUTPUT_DIR"

quality_measurement_annotations:
  timeout: 5h 00m
  rules:
    - when: manual
  variables:
    OUTPUT_DIR: "./output/$CI_COMMIT_TIMESTAMP"
  parallel:
    matrix:
      - BUCKET: bbp-external/seu
      - BUCKET: bbp/mouselight
      - BUCKET: public/sscx
      - BUCKET: public/thalamus
      - BUCKET: public/hippocampus
      - BUCKET: bbp/mmb-point-neuron-framework-model
  script:
  - > 
    python src/neuron_morphology/validation/quality_metric_resource.py 
    --username $SA_USERNAME --password $SA_PASSWORD --output_dir $OUTPUT_DIR --bucket $BUCKET --curated $CURATED 
    --really_update $REALLY_UPDATE --limit $LIMIT --push_to_staging $STAGING
  artifacts:
    paths:
      - "$OUTPUT_DIR"

feature_annotations:
  timeout: 10h 00m
  rules:
    - when: manual
  variables:
    OUTPUT_DIR: "./output/$CI_COMMIT_TIMESTAMP"
  parallel:
    matrix:
      - BUCKET: bbp-external/seu
      - BUCKET: bbp/mouselight
      - BUCKET: public/sscx
      - BUCKET: public/thalamus
      - BUCKET: public/hippocampus
      - BUCKET: bbp/mmb-point-neuron-framework-model
  script:
  - > 
    python src/neuron_morphology/feature_annotations/create_update_annotations.py 
    --username $SA_USERNAME --password $SA_PASSWORD --output_dir $OUTPUT_DIR --bucket $BUCKET --curated $CURATED
    --really_update $REALLY_UPDATE --limit $LIMIT --push_to_staging $STAGING
  artifacts:
    paths:
      - "$OUTPUT_DIR"


morphology_registration:
  rules:
    - when: manual
  variables:
    OUTPUT_DIR: "./output/$CI_COMMIT_TIMESTAMP"
  script:
  - > 
    python src/neuron_morphology/morphology_registration.py --username $SA_USERNAME --password $SA_PASSWORD --output_dir $OUTPUT_DIR
  artifacts:
    paths:
      - "$OUTPUT_DIR"


brain_region:
  rules:
    - when: manual
  variables:
    OUTPUT_DIR: "./output/$CI_COMMIT_TIMESTAMP"
  parallel:
    matrix:
      - BUCKET: bbp-external/seu
  script:
  - > 
    python src/neuron_morphology/validation/region_comparison.py 
    --username $SA_USERNAME --password $SA_PASSWORD --output_dir $OUTPUT_DIR --bucket $BUCKET --curated $CURATED
  artifacts:
    paths:
      - "$OUTPUT_DIR"

check_links:
  timeout: 5h 00m
  rules:
    - when: manual
  variables:
    OUTPUT_DIR: "./output/$CI_COMMIT_TIMESTAMP"
  parallel:
    matrix:
      - BUCKET: bbp-external/seu
      - BUCKET: bbp/mouselight
      - BUCKET: public/sscx
      - BUCKET: public/thalamus
      - BUCKET: public/hippocampus
      - BUCKET: bbp/mmb-point-neuron-framework-model
  script:
  - > 
    python src/neuron_morphology/validation/check_links.py 
    --username $SA_USERNAME --password $SA_PASSWORD --output_dir $OUTPUT_DIR --bucket $BUCKET --curated $CURATED
  artifacts:
    paths:
      - "$OUTPUT_DIR"


check_schema_validation:
  timeout: 8h 00m
  rules:
    - when: manual
  variables:
    OUTPUT_DIR: "./output/$BUCKET/$CI_COMMIT_TIMESTAMP"
  parallel:
    matrix:
      - BUCKET: public/sscx
      - BUCKET: public/thalamus
      - BUCKET: public/hippocampus
      - BUCKET: bbp/mmb-point-neuron-framework-model
      - BUCKET: bbp-external/seu
      - BUCKET: bbp/mouselight

  script:
  - > 
    python src/schemas/check_schema_validation.py 
    --username $SA_USERNAME --password $SA_PASSWORD --output_dir $OUTPUT_DIR --bucket $BUCKET
  artifacts:
    paths:
      - "$OUTPUT_DIR"
    when: always

check_changed_schemas:
  timeout: 8h 00m
  rules:
    - when: manual
  variables:
    OUTPUT_DIR: "./output/$BUCKET/$CI_COMMIT_TIMESTAMP"
  parallel:
    matrix:
      - BUCKET: public/sscx
      - BUCKET: public/thalamus
      - BUCKET: public/hippocampus
      - BUCKET: bbp/mmb-point-neuron-framework-model
      - BUCKET: bbp-external/seu
      - BUCKET: bbp/mouselight

  script:
  - > 
    python src/schemas/check_changed_schemas.py 
    --username $SA_USERNAME --password $SA_PASSWORD --output_dir $OUTPUT_DIR --bucket $BUCKET
    --changed_schemas_filepath $CHANGED_SCHEMAS
  artifacts:
    paths:
      - "$OUTPUT_DIR"
    when: always